(function(root){
  'use strict';
  const categories=['Hair & beauty','Clothing & shopping','Groceries & household','Children & childcare','Health & wellness','Gifts & family','Subscriptions','Transportation','Dining & entertainment','Housing & bills','Other'];
  const owners=['Mine','Partner’s','Shared'];
  function cents(value){if(!/^\d{1,9}(\.\d{1,2})?$/.test(String(value).trim()))throw Error('Enter a positive amount with no more than two decimal places.');const n=Math.round(Number(value)*100);if(n<=0)throw Error('Amount must be greater than zero.');return n;}
  function validDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}
  function validate(e){if(!validDate(e.date))throw Error('Choose a valid date.');if(!e.merchant?.trim())throw Error('Enter a merchant or description.');if(!Number.isSafeInteger(e.cents)||e.cents<=0)throw Error('Enter a valid amount.');if(!categories.includes(e.category)||!owners.includes(e.owner))throw Error('Choose a category and owner.');return {...e,merchant:e.merchant.trim().slice(0,150)};}
  function previous(month){const [y,m]=month.split('-').map(Number);return new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7);}
  function rows(data,month,owner='All'){return data.expenses.filter(e=>e.date.startsWith(month)&&(owner==='All'||e.owner===owner));}
  function summary(data,month,owner='All'){const selected=rows(data,month,owner),prior=rows(data,previous(month),owner);return {rows:selected,total:selected.reduce((s,e)=>s+e.cents,0),prior:prior.reduce((s,e)=>s+e.cents,0),hasPrior:prior.length>0,categories:categories.map(category=>({category,spent:selected.filter(e=>e.category===category).reduce((s,e)=>s+e.cents,0),budget:data.budgets[month]?.[category]||0}))};}
  function suggestion(s){if(!s.rows.length)return 'Add a few expenses to discover one useful money move for this month.';const over=s.categories.filter(c=>c.budget&&c.spent>c.budget).sort((a,b)=>(b.spent-b.budget)-(a.spent-a.budget))[0];if(over)return `${over.category} is ${money(over.spent-over.budget)} above your chosen monthly budget. Review one purchase in this category and decide whether to adjust next month’s plan.`;const recurring=s.rows.filter(e=>e.recurring);if(recurring.length)return `Review your ${recurring.length} marked recurring expense${recurring.length===1?'':'s'} and choose one to keep, renegotiate, or cancel if it no longer serves you.`;const top=s.categories.reduce((a,b)=>a.spent>b.spent?a:b);return `${top.category} is your largest recorded category at ${money(top.spent)}. Review it and choose a comfortable budget for next month.`;}
  function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);}
  function cell(v){let s=String(v);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
  function csv(s,detail){let r=[['Monday Money Move — spending report'],['Recorded spending',money(s.total)],[],['Category','Spent (USD)','Budget (USD)','Remaining (USD)'],...s.categories.filter(c=>c.spent||c.budget).map(c=>[c.category,(c.spent/100).toFixed(2),c.budget?(c.budget/100).toFixed(2):'',c.budget?((c.budget-c.spent)/100).toFixed(2):''])];if(detail)r.push([],['Date','Merchant','Amount (USD)','Category','Owner','Recurring'],...s.rows.map(e=>[e.date,e.merchant,(e.cents/100).toFixed(2),e.category,e.owner,e.recurring?'Yes':'No']));return '\uFEFF'+r.map(x=>x.map(cell).join(',')).join('\r\n');}
  function parse(text,month){return text.split(/\r\n?|\n|\u2028|\u2029/).map(line=>{const m=line.trim().match(/^(\d{4}-\d{2}-\d{2}|\d{1,2}[\/-]\d{1,2}(?:[\/-]\d{2,4})?)\s+(.+?)\s+\$?([\d,]+\.\d{2})\s*$/);if(!m)return null;let date=m[1];if(!/^\d{4}-\d{2}-\d{2}$/.test(date)){let [mm,dd,yy]=date.split(/[\/-]/);date=`${yy?(yy.length===2?'20'+yy:yy):month.slice(0,4)}-${mm.padStart(2,'0')}-${dd.padStart(2,'0')}`;}if(!validDate(date))return null;try{return {date,merchant:m[2],cents:cents(m[3].replaceAll(',','')),category:'Other',owner:'Mine',recurring:false};}catch{return null;}}).filter(Boolean);}
  const api={categories,owners,cents,validDate,validate,previous,rows,summary,suggestion,money,csv,parse};if(typeof module!=='undefined')module.exports=api;else root.SpendingCore=api;
})(typeof window!=='undefined'?window:globalThis);
